# Generated by Django 5.2.6 on 2025-11-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantlibraryentry',
            name='difficulty',
            field=models.CharField(default='Hard', max_length=100),
        ),
    ]
