# Generated by Django 5.2.6 on 2025-11-09 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_plantlibraryentry_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantlibraryentry',
            name='library',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Images/')),
                ('location_found', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('difficulty', models.CharField(default='Hard', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlantLibrary',
        ),
        migrations.DeleteModel(
            name='PlantLibraryEntry',
        ),
    ]
