# Generated by Django 5.2.6 on 2025-11-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_remove_plantlibraryentry_library_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='friendgroupmembership',
            name='join_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MID', 'MID'), ('HARD', 'HARD')], default='MID', max_length=5),
        ),
    ]
