# Generated by Django 5.2.8 on 2025-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('scientific_name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('common_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
