# Generated by Django 5.2.8 on 2025-11-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantnet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='dificulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Mid'), (3, 'Hard')], default=1),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='', upload_to='plant_photos/'),
            preserve_default=False,
        ),
    ]
