# Generated by Django 5.2.8 on 2025-11-09 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantnet', '0002_plant_dificulty_plant_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('current_challange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_challenge', to='plantnet.plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_challenge_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
